---
name: Flawfinder

on:
  push:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Flawfinder:
    name: Flawfinder

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run flawfinder
        uses: david-a-wheeler/flawfinder@2.0.19
        with:
          arguments: --sarif goveebttemplogger.cpp
          output: flawfinder_results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: Flawfinder
          sarif_file: flawfinder_results.sarif
